In [10]:
import numpy as np
from datascience import *
%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')
import warnings
warnings.simplefilter(action="ignore", category=FutureWarning)

# Lesson 5

1) Create an array containing 4 string elements: your first name, your last name, your birth
state and your favorite color.

a. Use a numpy function to make all elements uppercase.

b. Use a numpy function to count the number of times the letter “a” appears in each
element of your array.

c. Optional: Use a numpy function to find the length of each element in the array.
You may need to Google this.

In [16]:
array = make_array('devin', 'doyle', 'connecticut', 'steel')
np.char.capitalize(array)

array(['Devin', 'Doyle', 'Connecticut', 'Steel'], dtype='<U11')

In [17]:
np.char.count(array, 'a')

array([0, 0, 0, 0])

2) Create an array containing EVERY OTHER odd number starting with 1 and ending with
(and including) 41.

a. Use numpy to find the sum and the product of the elements of this array. NOTE:
This will require you to convert the elements of your array to floats using the
astype method.

b. Use numpy to take the natural log of each element.

c. Optional: The numpy function np.diff finds the difference between adjacent
elements of an array. Find the SUM of adjacent elements of this array.

In [31]:
odds = np.arange(1., 42., 4)
np.cumprod(odds)

array([1.00000000e+00, 5.00000000e+00, 4.50000000e+01, 5.85000000e+02,
       9.94500000e+03, 2.08845000e+05, 5.22112500e+06, 1.51412625e+08,
       4.99661662e+09, 1.84874815e+11, 7.57986742e+12])

In [32]:
np.log(odds)

array([0.        , 1.60943791, 2.19722458, 2.56494936, 2.83321334,
       3.04452244, 3.21887582, 3.36729583, 3.49650756, 3.61091791,
       3.71357207])